kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: pyapp-ingress
spec:
  rules:
    - host: pyapp.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: pyapp-service
              servicePort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
spec:
  selector:
    app: pyapp
  ports:
  - protocol: "TCP"
    port: 9000
    targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
spec:
  selector:
    matchLabels:
      app: pyapp
  replicas: 3
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: pyapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000